In [191]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [192]:
cdf = pd.read_csv("")
cdf

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

# Preprocessing

In [193]:
# Cheking the columns with object type
df = cdf
df.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [194]:
#Removing Car_id column
df = df.drop(['car_ID' , 'CarName'] , axis=1)

In [195]:
object_columns = []

#find the object datas
for col in df.columns:
    if df[col].dtype == 'object':
        object_columns.append(col)

print(object_columns)

['fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber', 'fuelsystem']

In [196]:
nonobject_columns = []

# find the non object datas
for col in df.columns:
    if df[col].dtype != 'object':
        nonobject_columns.append(col)


print(nonobject_columns)

['symboling', 'wheelbase', 'carlength', 'carwidth', 'carheight', 'curbweight', 'enginesize', 'boreratio', 'stroke', 'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price']

In [197]:
# Drop rows with missing values
df = df.dropna()
# Remove duplictes
df = df.drop_duplicates()

In [198]:
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col]= le.fit_transform(df[col])
df.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,0,1,2,2,0,94.5,171.2,65.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,1,0,0,3,1,0,99.8,176.6,66.2,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,1,0,0,3,0,0,99.4,176.6,66.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [199]:
nonobject_columns.remove('price')
print(nonobject_columns)

['symboling', 'wheelbase', 'carlength', 'carwidth', 'carheight', 'curbweight', 'enginesize', 'boreratio', 'stroke', 'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']

In [200]:
X = df.drop(['price'], axis=1)
y = df['price']
# Split data to X_train and y_train
X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size = 0.15 ,random_state = 10)
X_train0 , X_val , y_train0 , y_val = train_test_split(X_train,y_train ,test_size = 0.15 ,random_state = 10 )

In [201]:
scaler = StandardScaler()
X_train0[nonobject_columns]=scaler.fit_transform(X_train0[nonobject_columns])
X_val[nonobject_columns]= scaler.transform(X_val[nonobject_columns])
X_test[nonobject_columns] = scaler.transform(X_test[nonobject_columns])

In [202]:
# Create a StandardScaler object
scaler2 = StandardScaler()
X_train0[object_columns]=scaler2.fit_transform(X_train0[object_columns])
X_val[object_columns] = scaler2.transform(X_val[object_columns])
X_test[object_columns] = scaler2.transform(X_test[object_columns])

In [203]:
batch_size=10
train_data = tf.data.Dataset.from_tensor_slices((X_train0, y_train0))
train_data = train_data.shuffle(buffer_size=len(y_train0)).batch(batch_size)
val_data = tf.data.Dataset.from_tensor_slices((X_val, y_val))
val_data = val_data.batch(batch_size)

# Define a model

In [219]:
# Define the neural network model
model = keras.models.Sequential([
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(1)])

In [220]:
loss_fn = tf.keras.losses.MeanSquaredError()

In [221]:
optimizer = tf.keras.optimizers.Adam()
train_acc_metric = tf.keras.metrics.MeanAbsoluteError()
val_acc_metric = tf.keras.metrics.MeanAbsoluteError()

In [222]:
num_epochs = 101
train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []
for epoch in range(num_epochs):
    loss_train = []
    loss_vall = []
    for step, (x_batch_train, y_batch_train) in enumerate(train_data):
        with tf.GradientTape() as g:
            logits = model(x_batch_train , training=True)
            loss_value = loss_fn(y_true=y_batch_train , y_pred = logits)
        gradients = g.gradient(loss_value, model.trainable_weights)
        optimizer.apply_gradients(zip(gradients, model.trainable_weights))
        train_acc_metric.update_state(y_batch_train, logits)
        loss_train.append(loss_value)
    for step, (x_batch_val, y_batch_val) in enumerate(val_data):
        logits_val = model(x_batch_val)
        loss_value_val = loss_fn(y_true=y_batch_val, y_pred=logits_val)
        val_acc_metric.update_state(y_batch_val, logits_val)
        loss_vall.append(loss_value_val)
    train_acc = train_acc_metric.result()
    val_acc = val_acc_metric.result()
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)
    losses_train_mean = np.mean(loss_train)
    losses_val_mean = np.mean(loss_vall)
    train_losses.append(losses_train_mean)
    val_losses.append(losses_val_mean)
    if epoch == 1 or epoch % 10 == 0 and epoch != 0:
        print('\n Epoch %s: Train loss: %.4f  Validation Loss: %.4f, Train Accuracy: %.4f, Validation Accuracy %.4f' % (epoch, float(losses_train_mean), float(losses_val_mean), float(train_acc), float(val_acc)))

    train_acc_metric.reset_states()
    val_acc_metric.reset_states()

 Epoch 1: Train loss: 255118896.0000  Validation Loss: 173084624.0000, Train Accuracy: 13549.2275, Validation Accuracy 11875.7451

 Epoch 10: Train loss: 220930192.0000  Validation Loss: 142465808.0000, Train Accuracy: 12575.1182, Validation Accuracy 10784.1250

 Epoch 20: Train loss: 21957252.0000  Validation Loss: 17441666.0000, Train Accuracy: 3837.0881, Validation Accuracy 3296.7029

 Epoch 30: Train loss: 13270814.0000  Validation Loss: 11187349.0000, Train Accuracy: 2842.6882, Validation Accuracy 2533.7444

 Epoch 40: Train loss: 10012594.0000  Validation Loss: 9249205.0000, Train Accuracy: 2356.2217, Validation Accuracy 2272.2302

 Epoch 50: Train loss: 8545052.0000  Validation Loss: 8155458.0000, Train Accuracy: 2143.1211, Validation Accuracy 2167.5007

 Epoch 60: Train loss: 8240542.0000  Validation Loss: 7937716.0000, Train Accuracy: 2070.7766, Validation Accuracy 2142.9956

 Epoch 70: Train loss: 7073594.5000  Validation Loss: 7766118.0000, Train Accuracy: 1916.7512, Validation Accuracy 2142.7981

 Epoch 80: Train loss: 6915492.5000  Validation Loss: 7741351.5000, Train Accuracy: 1866.6387, Validation Accuracy 2139.0552

 Epoch 90: Train loss: 6409051.5000  Validation Loss: 7719420.0000, Train Accuracy: 1778.1335, Validation Accuracy 2137.4255

 Epoch 100: Train loss: 6194069.5000  Validation Loss: 7745714.5000, Train Accuracy: 1713.6287, Validation Accuracy 2141.7898